#goal definition
geometry_msgs/PoseStamped[] poses
string behavior_tree
geometry_msgs/Point[] c1
geometry_msgs/Point[] c2
bool[] is_curve_set
---
#result definition
std_msgs/Empty result
int8 return_code  #used by seer
---
#feedback definition
geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining
int16 number_of_poses_remaining